### ISSUE TITLE
app is crashed when ejected expo to bare-bone react native

### ISSUE THREAD

**Issue by ameinabdi** [ruddell/generator-jhipster-react-native#329] opened 2021-05-21 14:31 UTC
I have tried to eject the application and finished without any error also install pod but and I run the application on ios it didn't open and it crashed 

in meanwhile 

is there any way to generate a bare-bone react native app on the latest version of jhipster react native?

**Comment by ruddell** [comment] 2021-05-25 00:43
Thanks for reporting this issue.  It was caused by an accidental removal of a package from dependencies in https://github.com/ruddell/generator-jhipster-react-native/commit/c53258f3bd8c6107ba57895304953a4451a731b2

You can fix it in an existing project by installing that package with `npm install react-native-safe-area-context` and running pod install again.  Will be released shortly.

**Closed by ruddell** 2021-05-25 00:43 UTC

**Comment by ameinabdi** [comment] 2021-06-03 16:32
thanks for your response but still keeping crashing please try yours and eject project to see the issue

**Comment by ruddell** [comment] 2021-06-03 16:49
Did you try what I said in my last message?  I don't see any issues with the current release.  

Without an error message of some sort, I can't be much help.

**Comment by ameinabdi** [comment] 2021-06-03 17:31
yes i follow your instruction first i install ` npm install react-native-safe-area-contex` and install pod but nothing change then I update generator to v4.1.2 and  generate new project then eject expo but still crashing application when I run ios

**Comment by ruddell** [comment] 2021-06-04 03:36
Please provide an error message and your app config. The default options work fine when ejected from expo.
